shared:
  image: maven:3.6.3-jdk-8
  annotations:
    screwdriver.cd/ram: TURBO
    screwdriver.cd/cpu: TURBO
jobs:
  pr_build:
    requires: [~pr]
    steps:
      - ./gradlew build
  build: 
    requires: [~commit]
    steps:
      - ./gradlew build
  publish:
    environment:
        GPG_ENCPHRASE: something
    requires: [~build]
    secrets:
        # Publishing to NPM
        - GH_TOKEN
        - GPG_KEY
        - GPG_ENCPHRASE
        - OSSRH_TOKEN
        - OSSRH_USER
        - GPG_KEYNAME
        - GPG_SIGN_PASS
    steps:
      - . ./decrypt.sh
      - ./gradlew publish -debug
